'function example
DECLARE FUNCTION AVG ( X, Y )
CLS
INPUT " ENTER THE FIRST VALUE"; X
INPUT "ENTER THE SECOND VALUE";Y
PRINT" THE AVERAGE OF TWO VALUES"; AVG (X,Y)
END
FUNCTION AVG (X,Y)
AVG= (X+Y)/2
END FUNCTION